### ISSUE TITLE
aquarium no fog on safari

### ISSUE THREAD

**Issue by aholzer** [react-epfl/cross-aquarium#1]
![screen shot 2016-10-25 at 14 32 25](https://cloud.githubusercontent.com/assets/2970525/19686085/ffd72584-9abf-11e6-9d50-825622b9c7a2.png)

**Comment by romaincazier** [comment]
That's an issue I can't reproduce in my own Safari (v9.1), it's really strange... Maybe related to the disappearing fish bodies ?

**Comment by romaincazier** [comment]
Might be related to #11

**Comment by aholzer** [comment]
![screen shot 2016-11-02 at 09 43 35](https://cloud.githubusercontent.com/assets/2970525/19922024/f84268ac-a0e0-11e6-9702-77ade8d77bdf.png)

**Comment by aholzer** [comment]
Now the fog is there, but fish bodies and other images are missing

**Comment by romaincazier** [comment]
There was some changes made on cross-aquarium/index.html that need to be added. The images contain an attribute "data-src" which I use in javascript to dynamically add the src of the image depending on whether or not we are in zen mode @ahgentil

**Comment by romaincazier** [comment]
(and I just saw it's been added)
