### ISSUE TITLE
Items become wider, the more likes they receive

### ISSUE THREAD

**Issue by aholzer** [react-epfl/cross-aquarium#12]
use relative width with a min width for 0 likes and a max width for the most liked item in the space

**Comment by romaincazier** [comment]
I used the "voteScore" of the item for this. I also added a "changeScore" function which accepts an object with "_id" and "voteScore".

**Comment by romaincazier** [comment]
Just saw that subspaces don't have a "voteScore", just pushed a commit to take that into account

**Comment by ahgentil** [comment]
@romaincazier every item of the space (space or not) can have voteScore.
if the property is not there consider that voteScore is zero.

**Comment by romaincazier** [comment]
@ahgentil yes I defaulted to 0 if undefined
