### ISSUE TITLE
How can we pass the private mode flag to the readJson function?

### ISSUE THREAD

**Issue by ahgentil** [react-epfl/cross-aquarium#17]
@romaincazier You moved the `readJson` function inside the sketch file, in the `setup()` function: https://github.com/react-epfl/cross-aquarium/blob/master/js/sketch.js#L117

That was our way of launching the aquarium from our own html page. That function should be called by us so we can also pass the private mode flag.
Also, if we try to set the flag globally, it will not work because it will always be overwritten by this line: https://github.com/react-epfl/cross-aquarium/blob/master/js/jsonReader.js#L13, which always receives an `undefined` in the `privacy` parameter.

**Comment by ahgentil** [comment]
Previously, we were calling the function ourselves and passing the data in.
Then I noticed that everything was been drawn twice, and that's when I found that readJson was also being called from setup().

**Comment by romaincazier** [comment]
I did this because of #11. If we set the privacy setting globally I could just remove the line, or we could pass the setting to the `readJSON()` in `setup()`. Or we have to figure a way to execute the code on your side, after we make sure that everything is loaded (at the end of `setup()`)

**Comment by ahgentil** [comment]
If I just do the readJson after loading the sketch.js it will work?

**Comment by romaincazier** [comment]
Yes, because the `physics` object is initiated during `setup()` which is executed after all images are loaded

**Comment by ahgentil** [comment]
Ok. I'll check that option now 👍
I'll come back in a bit.

**Comment by ahgentil** [comment]
I'll create a global function on our html that the `setup` would call.
That function will already call `readJson` with the correct parameters (like privateMode).
I can do that change. Work on the other suff then.

**Comment by romaincazier** [comment]
(other stuff are done so you can already check/change if you want 👍 )
