### ISSUE TITLE
navigation should show the names of the subspaces, not subspace 1, subspace 2, etc

### ISSUE THREAD

**Issue by aholzer** [react-epfl/cross-aquarium#2]
![screen shot 2016-10-25 at 14 34 19](https://cloud.githubusercontent.com/assets/2970525/19686145/3d07fb54-9ac0-11e6-8f7d-e132c1c0f3e5.png)

**Comment by voz** [comment]
Should get the path from Graasp API, where we respond with the navigation structure, not to expose spaces that the user does not have access to.
