### ISSUE TITLE
App crashes when calculating comments' votes max/min

### ISSUE THREAD

**Issue by ahgentil** [react-epfl/cross-aquarium#22]
![screen shot 2016-11-02 at 16 30 24](https://cloud.githubusercontent.com/assets/7109418/19935262/ac3a08c8-a119-11e6-9e25-6163cad070ce.png)

**Comment by romaincazier** [comment]
Fixed :)

**Comment by romaincazier** [comment]
(lol we solved it at the same time...)

**Comment by ahgentil** [comment]
I noticed that when I got merge conflits
