### ISSUE TITLE
Update comment and item functions

### ISSUE THREAD

**Issue by ahgentil** [react-epfl/cross-aquarium#24]
updateComment(commentData)
- Update leaf size based on the score;

updateItem(itemData)
- Update rock 'thickness' based on the score;
- Update the 'tilting' based on the last modified date.

**Comment by romaincazier** [comment]
Is the itemData going to have the modified date even if it didn't change ? Right now there is no reference to the modified date on the item object, just the angle that is pre-calcuted when adding the item. So I can't compare to see if it changed.

**Comment by aholzer** [comment]
I guess if an item receives a change (such as a new comment or a like) then you can put it straight again, correct?

**Comment by romaincazier** [comment]
It depends on whether or not it does the same thing on the graasp system I guess ? @ahgentil

**Comment by aholzer** [comment]
After checking, We have it on a new like, but not on a new comment.
So you can straighten it on a new like (by this I mean an update item call), but not on a new comment

**Comment by romaincazier** [comment]
Ok finally got it to merge, I still have to figure out how Github works...
