### ISSUE TITLE
Comments and Items updating don't work properly

### ISSUE THREAD

**Issue by ahgentil** [react-epfl/cross-aquarium#26]
We've pushed some changes on our side to call updateComment() and updateItem() when a user upvotes/downvotes comments or likes/unlikes an item.

There's problems with both.
You can test it live on graasp.eu and debug.

For comments, test up/down voting and removing the vote (clicking on the current vote) - also try it in more than 1 item in the same aquarium.

For items, test like/unlike - also try it in more than 1 item in the same aquarium.

**Comment by romaincazier** [comment]
I corrected it in the last commit. There was some 'undefined' floating around
