### ISSUE TITLE
some fish do not have a body

### ISSUE THREAD

**Issue by aholzer** [react-epfl/cross-aquarium#3]
![screen shot 2016-10-25 at 14 36 08](https://cloud.githubusercontent.com/assets/2970525/19686189/6a54e52c-9ac0-11e6-97bd-f653731ca304.png)

**Comment by aholzer** [comment]
![screen shot 2016-10-25 at 16 44 51](https://cloud.githubusercontent.com/assets/2970525/19690874/6ae7706a-9ad2-11e6-9858-9f6626699446.png)

**Comment by romaincazier** [comment]
Might be related to #11
