### ISSUE TITLE
Add a private checkbox in graasp to switch between private and public aquarium navigation

### ISSUE THREAD

**Issue by aholzer** [react-epfl/cross-aquarium#5]

**Comment by voz** [comment]
Can someone add a description to get an idea how it's supposed to work?

**Comment by voz** [comment]
Just noticed that it in cross-aquarium repo, but if it concerns graasp (which I do not know if it does), it is probably better to have an in issue in  the Graasp repo.

**Comment by ahgentil** [comment]
This was already done on Graasp: https://github.com/react-epfl/graaspeu/commit/7b54f965f73540d342ebab77f41724da3caf465b
