### ISSUE TITLE
add a switch to change from zen to pop

### ISSUE THREAD

**Issue by aholzer** [react-epfl/cross-aquarium#6]
add a switch in the information tab to swith between pop and zen something like:

![screen shot 2016-10-25 at 14 40 18](https://cloud.githubusercontent.com/assets/2970525/19686359/0716ec52-9ac1-11e6-8247-fa85ab63a565.png)

**Comment by aholzer** [comment]
here is the design
![screen shot 2016-10-27 at 10 22 30](https://cloud.githubusercontent.com/assets/2970525/19759906/59fa7c58-9c2f-11e6-9387-6b76f634e9a0.png)

**Comment by romaincazier** [comment]
This would require a reload of the page, in order to re-generate the different elements using the right colors, is that ok ? @ahgentil @aholzer

**Comment by aholzer** [comment]
Yes it would reload the page with the adequate url (e.g. ?zen)

**Comment by romaincazier** [comment]
Yep, already done :)
