### ISSUE TITLE
Add link to parent in the navigation

### ISSUE THREAD

**Issue by aholzer** [react-epfl/cross-aquarium#8]

**Comment by romaincazier** [comment]
Is this something that has to be provided in the initial json ? What about if the user has no access to the parent ? Or if it's in public mode ? @ahgentil @aholzer

**Comment by aholzer** [comment]
We ll have to add it to the json 

For now you can just place an arrow up or an arrow back next to the current space to allow to go to the parent if such a jaon element is provided

**Comment by romaincazier** [comment]
Something like this ? 
![screen shot 2016-10-28 at 22 49 54](https://cloud.githubusercontent.com/assets/6616448/19827488/e2fe4e26-9d60-11e6-8417-901ee5a9297f.png)

**Comment by romaincazier** [comment]
I assume it would be a "parent" object (with "name", "_id", ...) in the "space" object ? @ahgentil

**Comment by aholzer** [comment]
👍🏽

**Comment by romaincazier** [comment]
Done !

**Comment by ahgentil** [comment]
@romaincazier do you need anything else other than the id? you mentioned `name` in the comment above, but if you're only gonna put the "little up arrow", you don't need anything else, right?

**Comment by romaincazier** [comment]
In the end the id is enough yes ! @ahgentil
