### ISSUE TITLE
Global flag to turn private mode on/off

### ISSUE THREAD

**Issue by ahgentil** [react-epfl/cross-aquarium#9]
Flag to allow turning the "bubbles" on or off.
This flag would be passed by us to the readJSON function when booting the aquarium:

```
var private = false|true;
readJSON(aquariumData, private);
```

Basically, if the flag is off, make it ignore the `createdByCurrentUser` field of items and comment.

`addItem` and `addComment` should also accept the same flag parameter when adding via sockets.

**Comment by romaincazier** [comment]
Is the "createdByCurrentUser" still sent ?

**Comment by ahgentil** [comment]
@romaincazier yes, `createdByCurrentUser` still sent

**Comment by romaincazier** [comment]
@ahgentil you must have seen it already but the variable is called "isSessionPrivate"
